# Generated by Django 4.0.6 on 2022-07-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='count',
            field=models.IntegerField(),
        ),
    ]
