# Generated by Django 4.0.6 on 2022-07-14 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_alter_urldata_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='posting_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
